services:
  server:
    container_name: cocode-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - CoCode
    ports:
      - "4000:3000"

  client:
    container_name: cocode-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - CoCode
    ports:
      - "4173:5173"
    depends_on:
      - server

networks:
  CoCode:
    driver: bridge
